FLOW-125: UI dropdown menu for verification types and FLOW-162: Phone Call Verification
tle-docusign/PowerPlatformConnectors pull request #2
Opened 2022-07-12 22:52 UTC by tle-docusign

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2022-07-13 08:10 UTC, angelga-docusign requested changes
Please fix the signing order comment. Then we can review the rest together.

2022-07-13 08:10 UTC, angelga-docusign commented on certified-connectors/DocuSignDemo/apiDefinition.swagger.json
> +            "name":"routingOrder",
@tle-docusign we still have this issue. You promoted routingorder to always show up in the UI. It shoudl be under advanced options. Just remove it from here, and restore it to under "AdditionalRecipientData".

2022-07-13 08:10 UTC, angelga-docusign commented on certified-connectors/DocuSignDemo/script.csx
> +        {"none", "None"},
How do we make sure that None is selected by default?

2022-07-13 08:10 UTC, angelga-docusign commented on certified-connectors/DocuSignDemo/script.csx
> -      signers[0]["recipientId"] = Guid.NewGuid();
Not sure why you're removing this

2022-07-13 20:12 UTC, angelga-docusign approved these changes
Let's fix the Node by default setting

2022-07-14 19:14 UTC, tle-docusign commented on certified-connectors/DocuSignDemo/script.csx
> -      signers[0]["recipientId"] = Guid.NewGuid();
I just relocated it to line 532

2022-07-15 18:41 UTC, angelga-docusign approved these changes

2022-07-15 18:41 UTC, angelga-docusign commented on certified-connectors/DocuSignDemo/apiDefinition.swagger.json
> +            "default": "None"
Nice!

2022-07-15 21:06 UTC, merged